rm ./styleguide/a-z-word-list-term-collections/a/media/abort-abortion/master
rm ./styleguide/a-z-word-list-term-collections/a/media/above/master
rm ./styleguide/a-z-word-list-term-collections/a/media/access-key/master
rm ./styleguide/a-z-word-list-term-collections/a/media/accessible/master
rm ./styleguide/a-z-word-list-term-collections/a/media/access/master
rm ./styleguide/a-z-word-list-term-collections/a/media/achievement/master
rm ./styleguide/a-z-word-list-term-collections/a/media/actionable/master
rm ./styleguide/a-z-word-list-term-collections/a/media/active-player-active-user/master
rm ./styleguide/a-z-word-list-term-collections/a/media/adapter/master
rm ./styleguide/a-z-word-list-term-collections/a/media/add-in-add-on/master
rm ./styleguide/a-z-word-list-term-collections/a/media/add/master
rm ./styleguide/a-z-word-list-term-collections/a/media/adjacent-selection/master
rm ./styleguide/a-z-word-list-term-collections/a/media/administer/master
rm ./styleguide/a-z-word-list-term-collections/a/media/administrator-admin/master
rm ./styleguide/a-z-word-list-term-collections/a/media/afterward/master
rm ./styleguide/a-z-word-list-term-collections/a/media/against/master
rm ./styleguide/a-z-word-list-term-collections/a/media/alarm/master
rm ./styleguide/a-z-word-list-term-collections/a/media/alert/master
rm ./styleguide/a-z-word-list-term-collections/a/media/alias/master
rm ./styleguide/a-z-word-list-term-collections/a/media/allow-allows/master
rm ./styleguide/a-z-word-list-term-collections/a/media/alphabetical/master
rm ./styleguide/a-z-word-list-term-collections/a/media/alphanumeric/master
rm ./styleguide/a-z-word-list-term-collections/a/media/am-pm/master
rm ./styleguide/a-z-word-list-term-collections/a/media/ampersand/master
rm ./styleguide/a-z-word-list-term-collections/a/media/and-or/master
rm ./styleguide/a-z-word-list-term-collections/a/media/and-so-on/master
rm ./styleguide/a-z-word-list-term-collections/a/media/antialiasing/master
rm ./styleguide/a-z-word-list-term-collections/a/media/antimalware/master
rm ./styleguide/a-z-word-list-term-collections/a/media/antispyware/master
rm ./styleguide/a-z-word-list-term-collections/a/media/antivirus/master
rm ./styleguide/a-z-word-list-term-collections/a/media/app-application/master
rm ./styleguide/a-z-word-list-term-collections/a/media/appears-displays/master
rm ./styleguide/a-z-word-list-term-collections/a/media/appendix-appendices/master
rm ./styleguide/a-z-word-list-term-collections/a/media/applet/master
rm ./styleguide/a-z-word-list-term-collections/a/media/application-developer-app-developer/master
rm ./styleguide/a-z-word-list-term-collections/a/media/application-file-app-file/master
rm ./styleguide/a-z-word-list-term-collections/a/media/application-icon-app-icon/master
rm ./styleguide/a-z-word-list-term-collections/a/media/application-window-app-window/master
rm ./styleguide/a-z-word-list-term-collections/a/media/argument-vs-parameter/master
rm ./styleguide/a-z-word-list-term-collections/a/media/arrow-keys/master
rm ./styleguide/a-z-word-list-term-collections/a/media/arrow/master
rm ./styleguide/a-z-word-list-term-collections/a/media/as-well-as/master
rm ./styleguide/a-z-word-list-term-collections/a/media/ask/master
rm ./styleguide/a-z-word-list-term-collections/a/media/assembly-language/master
rm ./styleguide/a-z-word-list-term-collections/a/media/assistive/master
rm ./styleguide/a-z-word-list-term-collections/a/media/assure-ensure-insure/master
rm ./styleguide/a-z-word-list-term-collections/a/media/asterisk/master
rm ./styleguide/a-z-word-list-term-collections/a/media/at-sign/master
rm ./styleguide/a-z-word-list-term-collections/a/media/attribute/master
rm ./styleguide/a-z-word-list-term-collections/a/media/audiobook/master
rm ./styleguide/a-z-word-list-term-collections/a/media/author/master
rm ./styleguide/a-z-word-list-term-collections/a/media/auto/master
rm ./styleguide/a-z-word-list-term-collections/b/media/back-end/master
rm ./styleguide/a-z-word-list-term-collections/b/media/back-up-backup/master
rm ./styleguide/a-z-word-list-term-collections/b/media/backbone/master
rm ./styleguide/a-z-word-list-term-collections/b/media/backlight/master
rm ./styleguide/a-z-word-list-term-collections/b/media/backspace/master
rm ./styleguide/a-z-word-list-term-collections/b/media/backtab/master
rm ./styleguide/a-z-word-list-term-collections/b/media/badge/master
rm ./styleguide/a-z-word-list-term-collections/b/media/baseline/master
rm ./styleguide/a-z-word-list-term-collections/b/media/baud/master
rm ./styleguide/a-z-word-list-term-collections/b/media/beep/master
rm ./styleguide/a-z-word-list-term-collections/b/media/below/master
rm ./styleguide/a-z-word-list-term-collections/b/media/beta/master
rm ./styleguide/a-z-word-list-term-collections/b/media/big-data/master
rm ./styleguide/a-z-word-list-term-collections/b/media/big-endian-little-endian/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bio/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bitmap/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bits-per-second/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bi/master
rm ./styleguide/a-z-word-list-term-collections/b/media/black-box/master
rm ./styleguide/a-z-word-list-term-collections/b/media/black-hat-hacker/master
rm ./styleguide/a-z-word-list-term-collections/b/media/blacklist/master
rm ./styleguide/a-z-word-list-term-collections/b/media/blade/master
rm ./styleguide/a-z-word-list-term-collections/b/media/blank/master
rm ./styleguide/a-z-word-list-term-collections/b/media/blog-blogger-blogroll-weblog/master
rm ./styleguide/a-z-word-list-term-collections/b/media/blu-ray-disc/master
rm ./styleguide/a-z-word-list-term-collections/b/media/blue-screen-bluescreen/master
rm ./styleguide/a-z-word-list-term-collections/b/media/board/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bold/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bookmark/master
rm ./styleguide/a-z-word-list-term-collections/b/media/boolean/master
rm ./styleguide/a-z-word-list-term-collections/b/media/boot/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bottom-left-bottom-right/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bounding-outline/master
rm ./styleguide/a-z-word-list-term-collections/b/media/box/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bps/master
rm ./styleguide/a-z-word-list-term-collections/b/media/breakpoint/master
rm ./styleguide/a-z-word-list-term-collections/b/media/broadcast/master
rm ./styleguide/a-z-word-list-term-collections/b/media/browse/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bug-fix/master
rm ./styleguide/a-z-word-list-term-collections/b/media/build/master
rm ./styleguide/a-z-word-list-term-collections/b/media/bulk/master
rm ./styleguide/a-z-word-list-term-collections/b/media/button/master
rm ./styleguide/a-z-word-list-term-collections/b/media/by/master
rm ./styleguide/a-z-word-list-term-collections/c/media/c-cplusplus-csharp/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cable/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cabling/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cache-vs-disk-cache/master
rm ./styleguide/a-z-word-list-term-collections/c/media/calendar/master
rm ./styleguide/a-z-word-list-term-collections/c/media/call-back-callback/master
rm ./styleguide/a-z-word-list-term-collections/c/media/call-out-callout/master
rm ./styleguide/a-z-word-list-term-collections/c/media/can-may/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cancel-canceled-canceling-cancellation/master
rm ./styleguide/a-z-word-list-term-collections/c/media/carry-out-vs-run/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cascading-style-sheets-css/master
rm ./styleguide/a-z-word-list-term-collections/c/media/catalog/master
rm ./styleguide/a-z-word-list-term-collections/c/media/category-axis/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cell-phone-cellular-phone/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cellular/master
rm ./styleguide/a-z-word-list-term-collections/c/media/center-on/master
rm ./styleguide/a-z-word-list-term-collections/c/media/character-set/master
rm ./styleguide/a-z-word-list-term-collections/c/media/chart/master
rm ./styleguide/a-z-word-list-term-collections/c/media/chat/master
rm ./styleguide/a-z-word-list-term-collections/c/media/check-check-box-check-mark/master
rm ./styleguide/a-z-word-list-term-collections/c/media/check-in/master
rm ./styleguide/a-z-word-list-term-collections/c/media/child-folder/master
rm ./styleguide/a-z-word-list-term-collections/c/media/choose/master
rm ./styleguide/a-z-word-list-term-collections/c/media/clear/master
rm ./styleguide/a-z-word-list-term-collections/c/media/clickstream/master
rm ./styleguide/a-z-word-list-term-collections/c/media/clickthrough/master
rm ./styleguide/a-z-word-list-term-collections/c/media/click/master
rm ./styleguide/a-z-word-list-term-collections/c/media/client-server/master
rm ./styleguide/a-z-word-list-term-collections/c/media/client-side/master
rm ./styleguide/a-z-word-list-term-collections/c/media/client/master
rm ./styleguide/a-z-word-list-term-collections/c/media/clipboard/master
rm ./styleguide/a-z-word-list-term-collections/c/media/close-button/master
rm ./styleguide/a-z-word-list-term-collections/c/media/close/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cloud-platform/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cloud-services/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cloud/master
rm ./styleguide/a-z-word-list-term-collections/c/media/code-page/master
rm ./styleguide/a-z-word-list-term-collections/c/media/code-point/master
rm ./styleguide/a-z-word-list-term-collections/c/media/codec/master
rm ./styleguide/a-z-word-list-term-collections/c/media/color-map/master
rm ./styleguide/a-z-word-list-term-collections/c/media/column-format/master
rm ./styleguide/a-z-word-list-term-collections/c/media/combo-box/master
rm ./styleguide/a-z-word-list-term-collections/c/media/command-button/master
rm ./styleguide/a-z-word-list-term-collections/c/media/command-line/master
rm ./styleguide/a-z-word-list-term-collections/c/media/command-prompt/master
rm ./styleguide/a-z-word-list-term-collections/c/media/command/master
rm ./styleguide/a-z-word-list-term-collections/c/media/community-cloud/master
rm ./styleguide/a-z-word-list-term-collections/c/media/compile/master
rm ./styleguide/a-z-word-list-term-collections/c/media/computer/master
rm ./styleguide/a-z-word-list-term-collections/c/media/compute/master
rm ./styleguide/a-z-word-list-term-collections/c/media/connect/master
rm ./styleguide/a-z-word-list-term-collections/c/media/console/master
rm ./styleguide/a-z-word-list-term-collections/c/media/context-menu/master
rm ./styleguide/a-z-word-list-term-collections/c/media/context-sensitive/master
rm ./styleguide/a-z-word-list-term-collections/c/media/contiguous-selection/master
rm ./styleguide/a-z-word-list-term-collections/c/media/control-menu-box/master
rm ./styleguide/a-z-word-list-term-collections/c/media/control-panel/master
rm ./styleguide/a-z-word-list-term-collections/c/media/control/master
rm ./styleguide/a-z-word-list-term-collections/c/media/corrupted/master
rm ./styleguide/a-z-word-list-term-collections/c/media/country-or-region/master
rm ./styleguide/a-z-word-list-term-collections/c/media/co/master
rm ./styleguide/a-z-word-list-term-collections/c/media/crash/master
rm ./styleguide/a-z-word-list-term-collections/c/media/current/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cut-and-paste/master
rm ./styleguide/a-z-word-list-term-collections/c/media/cyber/master
rm ./styleguide/a-z-word-list-term-collections/c/media/dash-core/master
rm ./styleguide/a-z-word-list-term-collections/d/media/data-binding/master
rm ./styleguide/a-z-word-list-term-collections/d/media/data-datum/master
rm ./styleguide/a-z-word-list-term-collections/d/media/data-record/master
rm ./styleguide/a-z-word-list-term-collections/d/media/database/master
rm ./styleguide/a-z-word-list-term-collections/d/media/datacenter/master
rm ./styleguide/a-z-word-list-term-collections/d/media/datagram/master
rm ./styleguide/a-z-word-list-term-collections/d/media/deaf-or-hard-of-hearing/master
rm ./styleguide/a-z-word-list-term-collections/d/media/debug/master
rm ./styleguide/a-z-word-list-term-collections/d/media/deceptive-software/master
rm ./styleguide/a-z-word-list-term-collections/d/media/decrement/master
rm ./styleguide/a-z-word-list-term-collections/d/media/default/master
rm ./styleguide/a-z-word-list-term-collections/d/media/defragment/master
rm ./styleguide/a-z-word-list-term-collections/d/media/deinstall/master
rm ./styleguide/a-z-word-list-term-collections/d/media/delete/master
rm ./styleguide/a-z-word-list-term-collections/d/media/demilitarized-zone-dmz/master
rm ./styleguide/a-z-word-list-term-collections/d/media/deprecated/master
rm ./styleguide/a-z-word-list-term-collections/d/media/depress-depressed/master
rm ./styleguide/a-z-word-list-term-collections/d/media/deselect/master
rm ./styleguide/a-z-word-list-term-collections/d/media/desktop/master
rm ./styleguide/a-z-word-list-term-collections/d/media/destination-drive-destination-file/master
rm ./styleguide/a-z-word-list-term-collections/d/media/destination/master
rm ./styleguide/a-z-word-list-term-collections/d/media/device-driver-driver/master
rm ./styleguide/a-z-word-list-term-collections/d/media/device/master
rm ./styleguide/a-z-word-list-term-collections/d/media/devops/master
rm ./styleguide/a-z-word-list-term-collections/d/media/dial-up/master
rm ./styleguide/a-z-word-list-term-collections/d/media/dialog-box-dialog/master
rm ./styleguide/a-z-word-list-term-collections/d/media/different/master
rm ./styleguide/a-z-word-list-term-collections/d/media/dimmed/master
rm ./styleguide/a-z-word-list-term-collections/d/media/direction-keys/master
rm ./styleguide/a-z-word-list-term-collections/d/media/directory/master
rm ./styleguide/a-z-word-list-term-collections/d/media/disable-disabled/master
rm ./styleguide/a-z-word-list-term-collections/d/media/disc/master
rm ./styleguide/a-z-word-list-term-collections/d/media/disjoint-selection/master
rm ./styleguide/a-z-word-list-term-collections/d/media/disk-resource/master
rm ./styleguide/a-z-word-list-term-collections/d/media/disk-space/master
rm ./styleguide/a-z-word-list-term-collections/d/media/disk/master
rm ./styleguide/a-z-word-list-term-collections/d/media/display-adapter-display-driver/master
rm ./styleguide/a-z-word-list-term-collections/d/media/displays-appears/master
rm ./styleguide/a-z-word-list-term-collections/d/media/dns/master
rm ./styleguide/a-z-word-list-term-collections/d/media/document/master
rm ./styleguide/a-z-word-list-term-collections/d/media/domain/master
rm ./styleguide/a-z-word-list-term-collections/d/media/dot-com/master
rm ./styleguide/a-z-word-list-term-collections/d/media/dotted-rectangle/master
rm ./styleguide/a-z-word-list-term-collections/d/media/double-buffering/master
rm ./styleguide/a-z-word-list-term-collections/d/media/double-click-double-clicking/master
rm ./styleguide/a-z-word-list-term-collections/d/media/downgrade/master
rm ./styleguide/a-z-word-list-term-collections/d/media/download/master
rm ./styleguide/a-z-word-list-term-collections/d/media/drag-and-drop/master
rm ./styleguide/a-z-word-list-term-collections/d/media/drive-name/master
rm ./styleguide/a-z-word-list-term-collections/d/media/drive/master
rm ./styleguide/a-z-word-list-term-collections/d/media/drop-down/master
rm ./styleguide/a-z-word-list-term-collections/d/media/dvd/master
rm ./styleguide/a-z-word-list-term-collections/d/media/dynamic-link-library-dll/master
rm ./styleguide/a-z-word-list-term-collections/d/media/dynamic-service-capacity/master
rm ./styleguide/a-z-word-list-term-collections/e/media/e-book/master
rm ./styleguide/a-z-word-list-term-collections/e/media/e-commerce/master
rm ./styleguide/a-z-word-list-term-collections/e/media/e-discovery/master
rm ./styleguide/a-z-word-list-term-collections/e/media/e-form-form/master
rm ./styleguide/a-z-word-list-term-collections/e/media/e-learning/master
rm ./styleguide/a-z-word-list-term-collections/e/media/e-words/master
rm ./styleguide/a-z-word-list-term-collections/e/media/earlier/master
rm ./styleguide/a-z-word-list-term-collections/e/media/edge/master
rm ./styleguide/a-z-word-list-term-collections/e/media/edutainment/master
rm ./styleguide/a-z-word-list-term-collections/e/media/eg/master
rm ./styleguide/a-z-word-list-term-collections/e/media/either-or/master
rm ./styleguide/a-z-word-list-term-collections/e/media/elastic-service-capacity/master
rm ./styleguide/a-z-word-list-term-collections/e/media/ellipsis-button/master
rm ./styleguide/a-z-word-list-term-collections/e/media/email/master
rm ./styleguide/a-z-word-list-term-collections/e/media/embed/master
rm ./styleguide/a-z-word-list-term-collections/e/media/emoticons-emoji/master
rm ./styleguide/a-z-word-list-term-collections/e/media/enable-enables/master
rm ./styleguide/a-z-word-list-term-collections/e/media/end-user-license-agreement-eula/master
rm ./styleguide/a-z-word-list-term-collections/e/media/endline/master
rm ./styleguide/a-z-word-list-term-collections/e/media/endpoint/master
rm ./styleguide/a-z-word-list-term-collections/e/media/end/master
rm ./styleguide/a-z-word-list-term-collections/e/media/ensure-insure-assure/master
rm ./styleguide/a-z-word-list-term-collections/e/media/enterprise/master
rm ./styleguide/a-z-word-list-term-collections/e/media/enter/master
rm ./styleguide/a-z-word-list-term-collections/e/media/entry-field/master
rm ./styleguide/a-z-word-list-term-collections/e/media/environment-variable/master
rm ./styleguide/a-z-word-list-term-collections/e/media/erase/master
rm ./styleguide/a-z-word-list-term-collections/e/media/et-al/master
rm ./styleguide/a-z-word-list-term-collections/e/media/etc/master
rm ./styleguide/a-z-word-list-term-collections/e/media/euro/master
rm ./styleguide/a-z-word-list-term-collections/e/media/executable-exe/master
rm ./styleguide/a-z-word-list-term-collections/e/media/execute/master
rm ./styleguide/a-z-word-list-term-collections/e/media/exit/master
rm ./styleguide/a-z-word-list-term-collections/e/media/expand-collapse/master
rm ./styleguide/a-z-word-list-term-collections/e/media/expose/master
rm ./styleguide/a-z-word-list-term-collections/e/media/extend/master
rm ./styleguide/a-z-word-list-term-collections/e/media/extension-file-name-extension/master
rm ./styleguide/a-z-word-list-term-collections/f/media/fail/master
rm ./styleguide/a-z-word-list-term-collections/f/media/false/master
rm ./styleguide/a-z-word-list-term-collections/f/media/family/master
rm ./styleguide/a-z-word-list-term-collections/f/media/far-east/master
rm ./styleguide/a-z-word-list-term-collections/f/media/far-left-far-right/master
rm ./styleguide/a-z-word-list-term-collections/f/media/favorite/master
rm ./styleguide/a-z-word-list-term-collections/f/media/fax/master
rm ./styleguide/a-z-word-list-term-collections/f/media/field/master
rm ./styleguide/a-z-word-list-term-collections/f/media/file-attributes/master
rm ./styleguide/a-z-word-list-term-collections/f/media/file-explorer/master
rm ./styleguide/a-z-word-list-term-collections/f/media/file-name-extension-extension/master
rm ./styleguide/a-z-word-list-term-collections/f/media/file-name/master
rm ./styleguide/a-z-word-list-term-collections/f/media/file/master
rm ./styleguide/a-z-word-list-term-collections/f/media/finalize/master
rm ./styleguide/a-z-word-list-term-collections/f/media/find-replace/master
rm ./styleguide/a-z-word-list-term-collections/f/media/fixed-disk/master
rm ./styleguide/a-z-word-list-term-collections/f/media/flick/master
rm ./styleguide/a-z-word-list-term-collections/f/media/flush-flush-to/master
rm ./styleguide/a-z-word-list-term-collections/f/media/flyout/master
rm ./styleguide/a-z-word-list-term-collections/f/media/folder-folder-icon/master
rm ./styleguide/a-z-word-list-term-collections/f/media/following/master
rm ./styleguide/a-z-word-list-term-collections/f/media/font-font-style/master
rm ./styleguide/a-z-word-list-term-collections/f/media/foo-foobar-fubar/master
rm ./styleguide/a-z-word-list-term-collections/f/media/footer/master
rm ./styleguide/a-z-word-list-term-collections/f/media/foreground-program/master
rm ./styleguide/a-z-word-list-term-collections/f/media/format-formatted-formatting/master
rm ./styleguide/a-z-word-list-term-collections/f/media/fourth-generation-language/master
rm ./styleguide/a-z-word-list-term-collections/f/media/frameset/master
rm ./styleguide/a-z-word-list-term-collections/f/media/freeze-frozen/master
rm ./styleguide/a-z-word-list-term-collections/f/media/friendly-name/master
rm ./styleguide/a-z-word-list-term-collections/f/media/from-vs-on/master
rm ./styleguide/a-z-word-list-term-collections/f/media/front-end/master
rm ./styleguide/a-z-word-list-term-collections/f/media/function/master
rm ./styleguide/a-z-word-list-term-collections/g/media/gallery/master
rm ./styleguide/a-z-word-list-term-collections/g/media/game-pad/master
rm ./styleguide/a-z-word-list-term-collections/g/media/garbage-collection-garbage-collector/master
rm ./styleguide/a-z-word-list-term-collections/g/media/general-protection-fault-gp-fault/master
rm ./styleguide/a-z-word-list-term-collections/g/media/gigabit/master
rm ./styleguide/a-z-word-list-term-collections/g/media/gigabyte/master
rm ./styleguide/a-z-word-list-term-collections/g/media/gigahertz/master
rm ./styleguide/a-z-word-list-term-collections/g/media/given/master
rm ./styleguide/a-z-word-list-term-collections/g/media/global/master
rm ./styleguide/a-z-word-list-term-collections/g/media/glyph/master
rm ./styleguide/a-z-word-list-term-collections/g/media/go-to/master
rm ./styleguide/a-z-word-list-term-collections/g/media/graphic-graphics-graphical/master
rm ./styleguide/a-z-word-list-term-collections/g/media/graphics-adapter/master
rm ./styleguide/a-z-word-list-term-collections/g/media/gray-grayed-out/master
rm ./styleguide/a-z-word-list-term-collections/g/media/greater-better/master
rm ./styleguide/a-z-word-list-term-collections/g/media/greylist/master
rm ./styleguide/a-z-word-list-term-collections/g/media/gridline/master
rm ./styleguide/a-z-word-list-term-collections/g/media/group-box/master
rm ./styleguide/a-z-word-list-term-collections/g/media/group-newsgroup/master
rm ./styleguide/a-z-word-list-term-collections/g/media/grow/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hack-hacker/master
rm ./styleguide/a-z-word-list-term-collections/h/media/half-inch/master
rm ./styleguide/a-z-word-list-term-collections/h/media/handle/master
rm ./styleguide/a-z-word-list-term-collections/h/media/handshake/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hang/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hard-coded/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hard-copy/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hard-drive/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hard-of-hearing/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hardwired/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hdmi/master
rm ./styleguide/a-z-word-list-term-collections/h/media/he-she/master
rm ./styleguide/a-z-word-list-term-collections/h/media/header/master
rm ./styleguide/a-z-word-list-term-collections/h/media/heading/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hearing-impaired/master
rm ./styleguide/a-z-word-list-term-collections/h/media/help/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hexadecimal/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hierarchical-menu/master
rm ./styleguide/a-z-word-list-term-collections/h/media/high-level-language-compiler/master
rm ./styleguide/a-z-word-list-term-collections/h/media/high-quality/master
rm ./styleguide/a-z-word-list-term-collections/h/media/high-resolution/master
rm ./styleguide/a-z-word-list-term-collections/h/media/higher/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hint/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hit/master
rm ./styleguide/a-z-word-list-term-collections/h/media/home-directory/master
rm ./styleguide/a-z-word-list-term-collections/h/media/home-home-page/master
rm ./styleguide/a-z-word-list-term-collections/h/media/honeypot/master
rm ./styleguide/a-z-word-list-term-collections/h/media/host-name/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hosted-service/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hosting-provider/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hot-key/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hot-link/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hot-spot-hotspot/master
rm ./styleguide/a-z-word-list-term-collections/h/media/how-how-to/master
rm ./styleguide/a-z-word-list-term-collections/h/media/html/master
rm ./styleguide/a-z-word-list-term-collections/h/media/http/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hub/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hybrid-cloud/master
rm ./styleguide/a-z-word-list-term-collections/h/media/hyperlink/master
rm ./styleguide/a-z-word-list-term-collections/i/media/iconize/master
rm ./styleguide/a-z-word-list-term-collections/i/media/icon/master
rm ./styleguide/a-z-word-list-term-collections/i/media/ie/master
rm ./styleguide/a-z-word-list-term-collections/i/media/if-vs-whether-vs-when/master
rm ./styleguide/a-z-word-list-term-collections/i/media/illegal/master
rm ./styleguide/a-z-word-list-term-collections/i/media/image-map/master
rm ./styleguide/a-z-word-list-term-collections/i/media/imbed/master
rm ./styleguide/a-z-word-list-term-collections/i/media/impact/master
rm ./styleguide/a-z-word-list-term-collections/i/media/inactive-inactive-state/master
rm ./styleguide/a-z-word-list-term-collections/i/media/inbound/master
rm ./styleguide/a-z-word-list-term-collections/i/media/incoming-outgoing/master
rm ./styleguide/a-z-word-list-term-collections/i/media/increment/master
rm ./styleguide/a-z-word-list-term-collections/i/media/indent-outdent/master
rm ./styleguide/a-z-word-list-term-collections/i/media/index-indexes-indices/master
rm ./styleguide/a-z-word-list-term-collections/i/media/info/master
rm ./styleguide/a-z-word-list-term-collections/i/media/infrastructure-as-a-service/master
rm ./styleguide/a-z-word-list-term-collections/i/media/initialize/master
rm ./styleguide/a-z-word-list-term-collections/i/media/initiate/master
rm ./styleguide/a-z-word-list-term-collections/i/media/inline/master
rm ./styleguide/a-z-word-list-term-collections/i/media/input-device/master
rm ./styleguide/a-z-word-list-term-collections/i/media/input-output/master
rm ./styleguide/a-z-word-list-term-collections/i/media/input/master
rm ./styleguide/a-z-word-list-term-collections/i/media/insecure/master
rm ./styleguide/a-z-word-list-term-collections/i/media/inside/master
rm ./styleguide/a-z-word-list-term-collections/i/media/install/master
rm ./styleguide/a-z-word-list-term-collections/i/media/instant-message-im/master
rm ./styleguide/a-z-word-list-term-collections/i/media/instantiate/master
rm ./styleguide/a-z-word-list-term-collections/i/media/insure-assure-ensure/master
rm ./styleguide/a-z-word-list-term-collections/i/media/interface/master
rm ./styleguide/a-z-word-list-term-collections/i/media/internet-connection-sharing/master
rm ./styleguide/a-z-word-list-term-collections/i/media/internet-explorer/master
rm ./styleguide/a-z-word-list-term-collections/i/media/internet-intranet-extranet/master
rm ./styleguide/a-z-word-list-term-collections/i/media/internet-service-provider/master
rm ./styleguide/a-z-word-list-term-collections/i/media/invalid-not-valid/master
rm ./styleguide/a-z-word-list-term-collections/i/media/invoke/master
rm ./styleguide/a-z-word-list-term-collections/i/media/ip-address/master
rm ./styleguide/a-z-word-list-term-collections/i/media/issue/master
rm ./styleguide/a-z-word-list-term-collections/i/media/it-pro-it-professional/master
rm ./styleguide/a-z-word-list-term-collections/i/media/italic/master
rm ./styleguide/a-z-word-list-term-collections/i/media/its-vs-its/master
rm ./styleguide/a-z-word-list-term-collections/j/media/java-jscript-javascript/master
rm ./styleguide/a-z-word-list-term-collections/j/media/join/master
rm ./styleguide/a-z-word-list-term-collections/j/media/joystick/master
rm ./styleguide/a-z-word-list-term-collections/j/media/jump/master
rm ./styleguide/a-z-word-list-term-collections/j/media/justify-justified/master
rm ./styleguide/a-z-word-list-term-collections/k/media/kerberos-protocol/master
rm ./styleguide/a-z-word-list-term-collections/k/media/key-combination/master
rm ./styleguide/a-z-word-list-term-collections/k/media/key-sequence/master
rm ./styleguide/a-z-word-list-term-collections/k/media/keyboard-shortcut/master
rm ./styleguide/a-z-word-list-term-collections/k/media/keypad/master
rm ./styleguide/a-z-word-list-term-collections/k/media/keypress-keystroke/master
rm ./styleguide/a-z-word-list-term-collections/k/media/kilobits-per-second/master
rm ./styleguide/a-z-word-list-term-collections/k/media/kilobit/master
rm ./styleguide/a-z-word-list-term-collections/k/media/kilobytes-per-second/master
rm ./styleguide/a-z-word-list-term-collections/k/media/kilobyte/master
rm ./styleguide/a-z-word-list-term-collections/k/media/kilohertz/master
rm ./styleguide/a-z-word-list-term-collections/k/media/knowledge-base/master
rm ./styleguide/a-z-word-list-term-collections/l/media/labeled-labeling/master
rm ./styleguide/a-z-word-list-term-collections/l/media/laptop/master
rm ./styleguide/a-z-word-list-term-collections/l/media/later/master
rm ./styleguide/a-z-word-list-term-collections/l/media/launch/master
rm ./styleguide/a-z-word-list-term-collections/l/media/lay-out-laid-out-layout/master
rm ./styleguide/a-z-word-list-term-collections/l/media/leading/master
rm ./styleguide/a-z-word-list-term-collections/l/media/leave/master
rm ./styleguide/a-z-word-list-term-collections/l/media/left-align-left-aligned/master
rm ./styleguide/a-z-word-list-term-collections/l/media/left-justify-left-justified/master
rm ./styleguide/a-z-word-list-term-collections/l/media/left-leftmost-left-hand/master
rm ./styleguide/a-z-word-list-term-collections/l/media/left-mouse-button/master
rm ./styleguide/a-z-word-list-term-collections/l/media/legacy/master
rm ./styleguide/a-z-word-list-term-collections/l/media/legal/master
rm ./styleguide/a-z-word-list-term-collections/l/media/less-vs-fewer-vs-under/master
rm ./styleguide/a-z-word-list-term-collections/l/media/let-lets/master
rm ./styleguide/a-z-word-list-term-collections/l/media/leverage/master
rm ./styleguide/a-z-word-list-term-collections/l/media/license-terms/master
rm ./styleguide/a-z-word-list-term-collections/l/media/like/master
rm ./styleguide/a-z-word-list-term-collections/l/media/line-of-business/master
rm ./styleguide/a-z-word-list-term-collections/l/media/line/master
rm ./styleguide/a-z-word-list-term-collections/l/media/link/master
rm ./styleguide/a-z-word-list-term-collections/l/media/list-box/master
rm ./styleguide/a-z-word-list-term-collections/l/media/load/master
rm ./styleguide/a-z-word-list-term-collections/l/media/lock-up/master
rm ./styleguide/a-z-word-list-term-collections/l/media/lock/master
rm ./styleguide/a-z-word-list-term-collections/l/media/log-on-log-off/master
rm ./styleguide/a-z-word-list-term-collections/l/media/low-resolution/master
rm ./styleguide/a-z-word-list-term-collections/l/media/lower-left-lower-right/master
rm ./styleguide/a-z-word-list-term-collections/l/media/lowercase/master
rm ./styleguide/a-z-word-list-term-collections/l/media/lower/master
rm ./styleguide/a-z-word-list-term-collections/m/media/machine-learning/master
rm ./styleguide/a-z-word-list-term-collections/m/media/machine/master
rm ./styleguide/a-z-word-list-term-collections/m/media/main-document/master
rm ./styleguide/a-z-word-list-term-collections/m/media/makefile/master
rm ./styleguide/a-z-word-list-term-collections/m/media/malicious-code/master
rm ./styleguide/a-z-word-list-term-collections/m/media/malicious-user/master
rm ./styleguide/a-z-word-list-term-collections/m/media/malware-malicious-software/master
rm ./styleguide/a-z-word-list-term-collections/m/media/management-information-systems/master
rm ./styleguide/a-z-word-list-term-collections/m/media/manipulate/master
rm ./styleguide/a-z-word-list-term-collections/m/media/marquee/master
rm ./styleguide/a-z-word-list-term-collections/m/media/master-slave-master-subordinate/master
rm ./styleguide/a-z-word-list-term-collections/m/media/mathematical/master
rm ./styleguide/a-z-word-list-term-collections/m/media/matrix-matrices/master
rm ./styleguide/a-z-word-list-term-collections/m/media/maximize-button-maximize/master
rm ./styleguide/a-z-word-list-term-collections/m/media/medium-media/master
rm ./styleguide/a-z-word-list-term-collections/m/media/megabits-per-second/master
rm ./styleguide/a-z-word-list-term-collections/m/media/megabit/master
rm ./styleguide/a-z-word-list-term-collections/m/media/megabyte/master
rm ./styleguide/a-z-word-list-term-collections/m/media/megahertz/master
rm ./styleguide/a-z-word-list-term-collections/m/media/member-function/master
rm ./styleguide/a-z-word-list-term-collections/m/media/memory-resident/master
rm ./styleguide/a-z-word-list-term-collections/m/media/memory/master
rm ./styleguide/a-z-word-list-term-collections/m/media/menu-item/master
rm ./styleguide/a-z-word-list-term-collections/m/media/message/master
rm ./styleguide/a-z-word-list-term-collections/m/media/metafile/master
rm ./styleguide/a-z-word-list-term-collections/m/media/microprocessor/master
rm ./styleguide/a-z-word-list-term-collections/m/media/microsoft-account/master
rm ./styleguide/a-z-word-list-term-collections/m/media/microsoft-edge/master
rm ./styleguide/a-z-word-list-term-collections/m/media/microsoft/master
rm ./styleguide/a-z-word-list-term-collections/m/media/micro/master
rm ./styleguide/a-z-word-list-term-collections/m/media/midnight/master
rm ./styleguide/a-z-word-list-term-collections/m/media/minimize-button-minimize/master
rm ./styleguide/a-z-word-list-term-collections/m/media/minus-sign/master
rm ./styleguide/a-z-word-list-term-collections/m/media/mip-mapping/master
rm ./styleguide/a-z-word-list-term-collections/m/media/mission-critical/master
rm ./styleguide/a-z-word-list-term-collections/m/media/mobile-device-mobile-phone/master
rm ./styleguide/a-z-word-list-term-collections/m/media/monitor/master
rm ./styleguide/a-z-word-list-term-collections/m/media/monospace/master
rm ./styleguide/a-z-word-list-term-collections/m/media/more-than-vs-over/master
rm ./styleguide/a-z-word-list-term-collections/m/media/mouse-over/master
rm ./styleguide/a-z-word-list-term-collections/m/media/movable/master
rm ./styleguide/a-z-word-list-term-collections/m/media/move/master
rm ./styleguide/a-z-word-list-term-collections/m/media/mpeg/master
rm ./styleguide/a-z-word-list-term-collections/m/media/multiple-selection/master
rm ./styleguide/a-z-word-list-term-collections/m/media/multiplication-sign/master
rm ./styleguide/a-z-word-list-term-collections/m/media/multitask-multitasking/master
rm ./styleguide/a-z-word-list-term-collections/m/media/multithreaded/master
rm ./styleguide/a-z-word-list-term-collections/m/media/multi/master
rm ./styleguide/a-z-word-list-term-collections/m/media/software-license-terms/master
rm ./styleguide/a-z-word-list-term-collections/n/media/namespace/master
rm ./styleguide/a-z-word-list-term-collections/n/media/nanosecond/master
rm ./styleguide/a-z-word-list-term-collections/n/media/native-language/master
rm ./styleguide/a-z-word-list-term-collections/n/media/natural-user-interface-nui/master
rm ./styleguide/a-z-word-list-term-collections/n/media/navigate/master
rm ./styleguide/a-z-word-list-term-collections/n/media/need/master
rm ./styleguide/a-z-word-list-term-collections/n/media/network-adapter/master
rm ./styleguide/a-z-word-list-term-collections/n/media/network-administrator/master
rm ./styleguide/a-z-word-list-term-collections/n/media/network-connection/master
rm ./styleguide/a-z-word-list-term-collections/n/media/network-drive/master
rm ./styleguide/a-z-word-list-term-collections/n/media/network/master
rm ./styleguide/a-z-word-list-term-collections/n/media/net/master
rm ./styleguide/a-z-word-list-term-collections/n/media/newsreader/master
rm ./styleguide/a-z-word-list-term-collections/n/media/nonadjacent-selection/master
rm ./styleguide/a-z-word-list-term-collections/n/media/noncontiguous-selection/master
rm ./styleguide/a-z-word-list-term-collections/n/media/nonprintable-nonprinting/master
rm ./styleguide/a-z-word-list-term-collections/n/media/non/master
rm ./styleguide/a-z-word-list-term-collections/n/media/normal-normally/master
rm ./styleguide/a-z-word-list-term-collections/n/media/notification-area/master
rm ./styleguide/a-z-word-list-term-collections/n/media/notification/master
rm ./styleguide/a-z-word-list-term-collections/n/media/null-terminated-null-terminating/master
rm ./styleguide/a-z-word-list-term-collections/n/media/null/master
rm ./styleguide/a-z-word-list-term-collections/n/media/number-sign/master
rm ./styleguide/a-z-word-list-term-collections/n/media/numeric/master
rm ./styleguide/a-z-word-list-term-collections/n/media/n/master
rm ./styleguide/a-z-word-list-term-collections/numbers-symbols/media/2d-two-dimensional/master
rm ./styleguide/a-z-word-list-term-collections/numbers-symbols/media/3d-three-dimensional/master
rm ./styleguide/a-z-word-list-term-collections/numbers-symbols/media/85-x-11-paper/master
rm ./styleguide/a-z-word-list-term-collections/numbers-symbols/media/twenty-four-seven/master
rm ./styleguide/a-z-word-list-term-collections/o/media/object/master
rm ./styleguide/a-z-word-list-term-collections/o/media/obsolete/master
rm ./styleguide/a-z-word-list-term-collections/o/media/off-premises-on-premises/master
rm ./styleguide/a-z-word-list-term-collections/o/media/offline/master
rm ./styleguide/a-z-word-list-term-collections/o/media/of/master
rm ./styleguide/a-z-word-list-term-collections/o/media/ok-okay/master
rm ./styleguide/a-z-word-list-term-collections/o/media/on-screen-keyboard/master
rm ./styleguide/a-z-word-list-term-collections/o/media/on-screen/master
rm ./styleguide/a-z-word-list-term-collections/o/media/on-the-fly/master
rm ./styleguide/a-z-word-list-term-collections/o/media/onboarding/master
rm ./styleguide/a-z-word-list-term-collections/o/media/once/master
rm ./styleguide/a-z-word-list-term-collections/o/media/online-services/master
rm ./styleguide/a-z-word-list-term-collections/o/media/online/master
rm ./styleguide/a-z-word-list-term-collections/o/media/onto/master
rm ./styleguide/a-z-word-list-term-collections/o/media/on/master
rm ./styleguide/a-z-word-list-term-collections/o/media/opcode/master
rm ./styleguide/a-z-word-list-term-collections/o/media/open-source/master
rm ./styleguide/a-z-word-list-term-collections/o/media/open/master
rm ./styleguide/a-z-word-list-term-collections/o/media/operating-environment-operating-system/master
rm ./styleguide/a-z-word-list-term-collections/o/media/opt-in-opt-out/master
rm ./styleguide/a-z-word-list-term-collections/o/media/option-button/master
rm ./styleguide/a-z-word-list-term-collections/o/media/output/master
rm ./styleguide/a-z-word-list-term-collections/o/media/outside/master
rm ./styleguide/a-z-word-list-term-collections/o/media/overwrite/master
rm ./styleguide/a-z-word-list-term-collections/o/media/over/master
rm ./styleguide/a-z-word-list-term-collections/p/media/p-code/master
rm ./styleguide/a-z-word-list-term-collections/p/media/page/master
rm ./styleguide/a-z-word-list-term-collections/p/media/palette/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pane/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pan/master
rm ./styleguide/a-z-word-list-term-collections/p/media/parameter/master
rm ./styleguide/a-z-word-list-term-collections/p/media/parent-child/master
rm ./styleguide/a-z-word-list-term-collections/p/media/parenthesis-parentheses/master
rm ./styleguide/a-z-word-list-term-collections/p/media/path/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pc/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pen/master
rm ./styleguide/a-z-word-list-term-collections/p/media/percent-percentage/master
rm ./styleguide/a-z-word-list-term-collections/p/media/perimeter-network/master
rm ./styleguide/a-z-word-list-term-collections/p/media/peripheral/master
rm ./styleguide/a-z-word-list-term-collections/p/media/permissions/master
rm ./styleguide/a-z-word-list-term-collections/p/media/per/master
rm ./styleguide/a-z-word-list-term-collections/p/media/phone/master
rm ./styleguide/a-z-word-list-term-collections/p/media/photo/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pin-unpin/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pinch/master
rm ./styleguide/a-z-word-list-term-collections/p/media/ping-ping/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pipe/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pixel/master
rm ./styleguide/a-z-word-list-term-collections/p/media/placeholder/master
rm ./styleguide/a-z-word-list-term-collections/p/media/plaintext-plain-text/master
rm ./styleguide/a-z-word-list-term-collections/p/media/platform-as-a-service/master
rm ./styleguide/a-z-word-list-term-collections/p/media/platform/master
rm ./styleguide/a-z-word-list-term-collections/p/media/playlist/master
rm ./styleguide/a-z-word-list-term-collections/p/media/please/master
rm ./styleguide/a-z-word-list-term-collections/p/media/plug-and-play/master
rm ./styleguide/a-z-word-list-term-collections/p/media/plug-in/master
rm ./styleguide/a-z-word-list-term-collections/p/media/plus-sign/master
rm ./styleguide/a-z-word-list-term-collections/p/media/point-to/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pointer/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pop-up/master
rm ./styleguide/a-z-word-list-term-collections/p/media/port/master
rm ./styleguide/a-z-word-list-term-collections/p/media/postal-code/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pound-key-pound-sign/master
rm ./styleguide/a-z-word-list-term-collections/p/media/power-cord/master
rm ./styleguide/a-z-word-list-term-collections/p/media/power-down-power-up-power-off-power-on/master
rm ./styleguide/a-z-word-list-term-collections/p/media/power-user/master
rm ./styleguide/a-z-word-list-term-collections/p/media/preceding/master
rm ./styleguide/a-z-word-list-term-collections/p/media/press-and-hold/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pre/master
rm ./styleguide/a-z-word-list-term-collections/p/media/print-printout/master
rm ./styleguide/a-z-word-list-term-collections/p/media/print-queue-printer-queue/master
rm ./styleguide/a-z-word-list-term-collections/p/media/private-cloud-hosted-private-cloud/master
rm ./styleguide/a-z-word-list-term-collections/p/media/privileges/master
rm ./styleguide/a-z-word-list-term-collections/p/media/profile/master
rm ./styleguide/a-z-word-list-term-collections/p/media/program-file/master
rm ./styleguide/a-z-word-list-term-collections/p/media/program/master
rm ./styleguide/a-z-word-list-term-collections/p/media/prompt/master
rm ./styleguide/a-z-word-list-term-collections/p/media/property-sheet-property-page/master
rm ./styleguide/a-z-word-list-term-collections/p/media/property/master
rm ./styleguide/a-z-word-list-term-collections/p/media/prop/master
rm ./styleguide/a-z-word-list-term-collections/p/media/protected-mode/master
rm ./styleguide/a-z-word-list-term-collections/p/media/public-cloud/master
rm ./styleguide/a-z-word-list-term-collections/p/media/pull-down/master
rm ./styleguide/a-z-word-list-term-collections/p/media/purge/master
rm ./styleguide/a-z-word-list-term-collections/p/media/push-button/master
rm ./styleguide/a-z-word-list-term-collections/q/media/quality-high-quality/master
rm ./styleguide/a-z-word-list-term-collections/q/media/quit/master
rm ./styleguide/a-z-word-list-term-collections/r/media/radio-button/master
rm ./styleguide/a-z-word-list-term-collections/r/media/ragged-right/master
rm ./styleguide/a-z-word-list-term-collections/r/media/ram/master
rm ./styleguide/a-z-word-list-term-collections/r/media/range-selection/master
rm ./styleguide/a-z-word-list-term-collections/r/media/read-only/master
rm ./styleguide/a-z-word-list-term-collections/r/media/read-write-read-write-permission/master
rm ./styleguide/a-z-word-list-term-collections/r/media/real-time/master
rm ./styleguide/a-z-word-list-term-collections/r/media/reboot/master
rm ./styleguide/a-z-word-list-term-collections/r/media/recommend/master
rm ./styleguide/a-z-word-list-term-collections/r/media/recycle-bin/master
rm ./styleguide/a-z-word-list-term-collections/r/media/refresh/master
rm ./styleguide/a-z-word-list-term-collections/r/media/registry-registry-settings/master
rm ./styleguide/a-z-word-list-term-collections/r/media/reinitialize/master
rm ./styleguide/a-z-word-list-term-collections/r/media/rem-statement/master
rm ./styleguide/a-z-word-list-term-collections/r/media/remote/master
rm ./styleguide/a-z-word-list-term-collections/r/media/remove/master
rm ./styleguide/a-z-word-list-term-collections/r/media/replace/master
rm ./styleguide/a-z-word-list-term-collections/r/media/restart/master
rm ./styleguide/a-z-word-list-term-collections/r/media/restore/master
rm ./styleguide/a-z-word-list-term-collections/r/media/reverse-video/master
rm ./styleguide/a-z-word-list-term-collections/r/media/re/master
rm ./styleguide/a-z-word-list-term-collections/r/media/right-align-right-aligned/master
rm ./styleguide/a-z-word-list-term-collections/r/media/right-click/master
rm ./styleguide/a-z-word-list-term-collections/r/media/right-justify-right-justified/master
rm ./styleguide/a-z-word-list-term-collections/r/media/right-mouse-button/master
rm ./styleguide/a-z-word-list-term-collections/r/media/right-rightmost-right-hand/master
rm ./styleguide/a-z-word-list-term-collections/r/media/rights/master
rm ./styleguide/a-z-word-list-term-collections/r/media/roman/master
rm ./styleguide/a-z-word-list-term-collections/r/media/rom/master
rm ./styleguide/a-z-word-list-term-collections/r/media/root-directory/master
rm ./styleguide/a-z-word-list-term-collections/r/media/rotate/master
rm ./styleguide/a-z-word-list-term-collections/r/media/run-vs-execute/master
rm ./styleguide/a-z-word-list-term-collections/r/media/running-foot-running-head/master
rm ./styleguide/a-z-word-list-term-collections/r/media/runs-vs-runs-on/master
rm ./styleguide/a-z-word-list-term-collections/r/media/runtime/master
rm ./styleguide/a-z-word-list-term-collections/s/media/s-es/master
rm ./styleguide/a-z-word-list-term-collections/s/media/sample-vs-preview/master
rm ./styleguide/a-z-word-list-term-collections/s/media/save/master
rm ./styleguide/a-z-word-list-term-collections/s/media/scan-line/master
rm ./styleguide/a-z-word-list-term-collections/s/media/screen-resolution/master
rm ./styleguide/a-z-word-list-term-collections/s/media/screened-subnet/master
rm ./styleguide/a-z-word-list-term-collections/s/media/screenshot/master
rm ./styleguide/a-z-word-list-term-collections/s/media/screen/master
rm ./styleguide/a-z-word-list-term-collections/s/media/script-scriptlet/master
rm ./styleguide/a-z-word-list-term-collections/s/media/scroll-bar-scroll-arrow-scroll-box/master
rm ./styleguide/a-z-word-list-term-collections/s/media/scroll/master
rm ./styleguide/a-z-word-list-term-collections/s/media/search-and-replace/master
rm ./styleguide/a-z-word-list-term-collections/s/media/search-box/master
rm ./styleguide/a-z-word-list-term-collections/s/media/secondary-menu/master
rm ./styleguide/a-z-word-list-term-collections/s/media/select/master
rm ./styleguide/a-z-word-list-term-collections/s/media/service-oriented-architecture-soa/master
rm ./styleguide/a-z-word-list-term-collections/s/media/set-specify/master
rm ./styleguide/a-z-word-list-term-collections/s/media/set-top-box/master
rm ./styleguide/a-z-word-list-term-collections/s/media/set-up-setup/master
rm ./styleguide/a-z-word-list-term-collections/s/media/setting-value/master
rm ./styleguide/a-z-word-list-term-collections/s/media/shaded/master
rm ./styleguide/a-z-word-list-term-collections/s/media/shell/master
rm ./styleguide/a-z-word-list-term-collections/s/media/ship/master
rm ./styleguide/a-z-word-list-term-collections/s/media/shortcut-shortcut-menu/master
rm ./styleguide/a-z-word-list-term-collections/s/media/should-vs-must/master
rm ./styleguide/a-z-word-list-term-collections/s/media/shut-down-shutdown/master
rm ./styleguide/a-z-word-list-term-collections/s/media/sign-in-sign-out/master
rm ./styleguide/a-z-word-list-term-collections/s/media/simply/master
rm ./styleguide/a-z-word-list-term-collections/s/media/site-map/master
rm ./styleguide/a-z-word-list-term-collections/s/media/site/master
rm ./styleguide/a-z-word-list-term-collections/s/media/size-resize/master
rm ./styleguide/a-z-word-list-term-collections/s/media/sleep/master
rm ./styleguide/a-z-word-list-term-collections/s/media/slider/master
rm ./styleguide/a-z-word-list-term-collections/s/media/slideshow/master
rm ./styleguide/a-z-word-list-term-collections/s/media/small-caps/master
rm ./styleguide/a-z-word-list-term-collections/s/media/smart-card/master
rm ./styleguide/a-z-word-list-term-collections/s/media/smartphone/master
rm ./styleguide/a-z-word-list-term-collections/s/media/snap-in/master
rm ./styleguide/a-z-word-list-term-collections/s/media/soft-copy/master
rm ./styleguide/a-z-word-list-term-collections/s/media/software-as-a-service-saas/master
rm ./styleguide/a-z-word-list-term-collections/s/media/software-plus-services/master
rm ./styleguide/a-z-word-list-term-collections/s/media/sorry/master
rm ./styleguide/a-z-word-list-term-collections/s/media/spam/master
rm ./styleguide/a-z-word-list-term-collections/s/media/specification/master
rm ./styleguide/a-z-word-list-term-collections/s/media/spell-checker/master
rm ./styleguide/a-z-word-list-term-collections/s/media/spin-box/master
rm ./styleguide/a-z-word-list-term-collections/s/media/split-bar-split-box/master
rm ./styleguide/a-z-word-list-term-collections/s/media/spoofing/master
rm ./styleguide/a-z-word-list-term-collections/s/media/spreadsheet-vs-workbook/master
rm ./styleguide/a-z-word-list-term-collections/s/media/spyware/master
rm ./styleguide/a-z-word-list-term-collections/s/media/sql-sql-server/master
rm ./styleguide/a-z-word-list-term-collections/s/media/start-button-start-menu/master
rm ./styleguide/a-z-word-list-term-collections/s/media/start-page/master
rm ./styleguide/a-z-word-list-term-collections/s/media/start-restart/master
rm ./styleguide/a-z-word-list-term-collections/s/media/start-up-startup/master
rm ./styleguide/a-z-word-list-term-collections/s/media/status-bar/master
rm ./styleguide/a-z-word-list-term-collections/s/media/stop-stop-responding/master
rm ./styleguide/a-z-word-list-term-collections/s/media/storage-storage-device/master
rm ./styleguide/a-z-word-list-term-collections/s/media/store-marketplace-gallery/master
rm ./styleguide/a-z-word-list-term-collections/s/media/stream-streaming/master
rm ./styleguide/a-z-word-list-term-collections/s/media/stretch/master
rm ./styleguide/a-z-word-list-term-collections/s/media/struct-structure/master
rm ./styleguide/a-z-word-list-term-collections/s/media/style-sheet/master
rm ./styleguide/a-z-word-list-term-collections/s/media/subaddress/master
rm ./styleguide/a-z-word-list-term-collections/s/media/subclass/master
rm ./styleguide/a-z-word-list-term-collections/s/media/sub/master
rm ./styleguide/a-z-word-list-term-collections/s/media/surf/master
rm ./styleguide/a-z-word-list-term-collections/s/media/swipe/master
rm ./styleguide/a-z-word-list-term-collections/s/media/switch/master
rm ./styleguide/a-z-word-list-term-collections/s/media/symbol/master
rm ./styleguide/a-z-word-list-term-collections/s/media/sync/master
rm ./styleguide/a-z-word-list-term-collections/s/media/system-administrator/master
rm ./styleguide/a-z-word-list-term-collections/s/media/system-prompt/master
rm ./styleguide/a-z-word-list-term-collections/s/media/system-software/master
rm ./styleguide/a-z-word-list-term-collections/s/media/system-tray/master
rm ./styleguide/a-z-word-list-term-collections/t/media/table-of-contents/master
rm ./styleguide/a-z-word-list-term-collections/t/media/tablet/master
rm ./styleguide/a-z-word-list-term-collections/t/media/tab/master
rm ./styleguide/a-z-word-list-term-collections/t/media/taiwan/master
rm ./styleguide/a-z-word-list-term-collections/t/media/tap-double-tap-tap-and-hold/master
rm ./styleguide/a-z-word-list-term-collections/t/media/target-drive-target-file/master
rm ./styleguide/a-z-word-list-term-collections/t/media/taskbar/master
rm ./styleguide/a-z-word-list-term-collections/t/media/terabyte/master
rm ./styleguide/a-z-word-list-term-collections/t/media/terminate/master
rm ./styleguide/a-z-word-list-term-collections/t/media/text-box/master
rm ./styleguide/a-z-word-list-term-collections/t/media/text-text-message/master
rm ./styleguide/a-z-word-list-term-collections/t/media/thank-you/master
rm ./styleguide/a-z-word-list-term-collections/t/media/that-vs-which/master
rm ./styleguide/a-z-word-list-term-collections/t/media/tile-live-tile/master
rm ./styleguide/a-z-word-list-term-collections/t/media/time-out/master
rm ./styleguide/a-z-word-list-term-collections/t/media/time-stamp/master
rm ./styleguide/a-z-word-list-term-collections/t/media/to-do/master
rm ./styleguide/a-z-word-list-term-collections/t/media/toast/master
rm ./styleguide/a-z-word-list-term-collections/t/media/toggle/master
rm ./styleguide/a-z-word-list-term-collections/t/media/tone/master
rm ./styleguide/a-z-word-list-term-collections/t/media/toolkit/master
rm ./styleguide/a-z-word-list-term-collections/t/media/tool/master
rm ./styleguide/a-z-word-list-term-collections/t/media/top-left-top-right/master
rm ./styleguide/a-z-word-list-term-collections/t/media/top-level-folder/master
rm ./styleguide/a-z-word-list-term-collections/t/media/touchpad/master
rm ./styleguide/a-z-word-list-term-collections/t/media/touchscreen/master
rm ./styleguide/a-z-word-list-term-collections/t/media/toward/master
rm ./styleguide/a-z-word-list-term-collections/t/media/trailing/master
rm ./styleguide/a-z-word-list-term-collections/t/media/trojan-horse-trojan/master
rm ./styleguide/a-z-word-list-term-collections/t/media/turn-on-turn-off/master
rm ./styleguide/a-z-word-list-term-collections/t/media/turnkey/master
rm ./styleguide/a-z-word-list-term-collections/t/media/type/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/accessibility-terms/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/bits-bytes-terms/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/cloud-computing-terms/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/computer-device-terms/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/date-time-terms/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/keys-keyboard-shortcuts/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/legal-red-flag-terms/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/mouse-mouse-interaction-terms/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/security-safety-privacy-terms/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/special-characters/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/touch-pen-interaction-terms/master
rm ./styleguide/a-z-word-list-term-collections/term-collections/media/units-of-measure-terms/master
rm ./styleguide/a-z-word-list-term-collections/u/media/uk/master
rm ./styleguide/a-z-word-list-term-collections/u/media/ultrabook/master
rm ./styleguide/a-z-word-list-term-collections/u/media/unavailable/master
rm ./styleguide/a-z-word-list-term-collections/u/media/uncheck-unmark-unselect/master
rm ./styleguide/a-z-word-list-term-collections/u/media/undelete/master
rm ./styleguide/a-z-word-list-term-collections/u/media/underline-vs-underscore/master
rm ./styleguide/a-z-word-list-term-collections/u/media/undo/master
rm ./styleguide/a-z-word-list-term-collections/u/media/uninstall/master
rm ./styleguide/a-z-word-list-term-collections/u/media/unregister/master
rm ./styleguide/a-z-word-list-term-collections/u/media/unwanted-software/master
rm ./styleguide/a-z-word-list-term-collections/u/media/un/master
rm ./styleguide/a-z-word-list-term-collections/u/media/upgrade/master
rm ./styleguide/a-z-word-list-term-collections/u/media/upload/master
rm ./styleguide/a-z-word-list-term-collections/u/media/upnp/master
rm ./styleguide/a-z-word-list-term-collections/u/media/upper-left-upper-right/master
rm ./styleguide/a-z-word-list-term-collections/u/media/uppercase/master
rm ./styleguide/a-z-word-list-term-collections/u/media/upsize/master
rm ./styleguide/a-z-word-list-term-collections/u/media/upward/master
rm ./styleguide/a-z-word-list-term-collections/u/media/url/master
rm ./styleguide/a-z-word-list-term-collections/u/media/usable/master
rm ./styleguide/a-z-word-list-term-collections/u/media/use-terms/master
rm ./styleguide/a-z-word-list-term-collections/u/media/user-end-user/master
rm ./styleguide/a-z-word-list-term-collections/u/media/user-rights/master
rm ./styleguide/a-z-word-list-term-collections/u/media/using-by-using-with/master
rm ./styleguide/a-z-word-list-term-collections/u/media/us/master
rm ./styleguide/a-z-word-list-term-collections/u/media/utility/master
rm ./styleguide/a-z-word-list-term-collections/v/media/value-axis/master
rm ./styleguide/a-z-word-list-term-collections/v/media/versus-vs/master
rm ./styleguide/a-z-word-list-term-collections/v/media/video-call-videoconference/master
rm ./styleguide/a-z-word-list-term-collections/v/media/video-card/master
rm ./styleguide/a-z-word-list-term-collections/v/media/video-display/master
rm ./styleguide/a-z-word-list-term-collections/v/media/video-driver/master
rm ./styleguide/a-z-word-list-term-collections/v/media/video-game/master
rm ./styleguide/a-z-word-list-term-collections/v/media/virtualize/master
rm ./styleguide/a-z-word-list-term-collections/v/media/virtual/master
rm ./styleguide/a-z-word-list-term-collections/v/media/visit/master
rm ./styleguide/a-z-word-list-term-collections/v/media/voicemail/master
rm ./styleguide/a-z-word-list-term-collections/v/media/vulnerability/master
rm ./styleguide/a-z-word-list-term-collections/w/media/w3c/master
rm ./styleguide/a-z-word-list-term-collections/w/media/want/master
rm ./styleguide/a-z-word-list-term-collections/w/media/web-services/master
rm ./styleguide/a-z-word-list-term-collections/w/media/web-world-wide-web-www/master
rm ./styleguide/a-z-word-list-term-collections/w/media/we/master
rm ./styleguide/a-z-word-list-term-collections/w/media/where/master
rm ./styleguide/a-z-word-list-term-collections/w/media/while/master
rm ./styleguide/a-z-word-list-term-collections/w/media/white-hat-hacker/master
rm ./styleguide/a-z-word-list-term-collections/w/media/white-paper/master
rm ./styleguide/a-z-word-list-term-collections/w/media/white-space/master
rm ./styleguide/a-z-word-list-term-collections/w/media/whitelist/master
rm ./styleguide/a-z-word-list-term-collections/w/media/who-vs-that/master
rm ./styleguide/a-z-word-list-term-collections/w/media/wi-fi/master
rm ./styleguide/a-z-word-list-term-collections/w/media/wildcard-character/master
rm ./styleguide/a-z-word-list-term-collections/w/media/windows-7-windows-8-windows-10/master
rm ./styleguide/a-z-word-list-term-collections/w/media/windows-explorer/master
rm ./styleguide/a-z-word-list-term-collections/w/media/windows-windows-based/master
rm ./styleguide/a-z-word-list-term-collections/w/media/window/master
rm ./styleguide/a-z-word-list-term-collections/w/media/wireframe/master
rm ./styleguide/a-z-word-list-term-collections/w/media/wireless/master
rm ./styleguide/a-z-word-list-term-collections/w/media/wizard/master
rm ./styleguide/a-z-word-list-term-collections/w/media/word-processing/master
rm ./styleguide/a-z-word-list-term-collections/w/media/wordwrap-wordwrapping/master
rm ./styleguide/a-z-word-list-term-collections/w/media/work-area-workspace/master
rm ./styleguide/a-z-word-list-term-collections/w/media/work-style/master
rm ./styleguide/a-z-word-list-term-collections/w/media/workgroup/master
rm ./styleguide/a-z-word-list-term-collections/w/media/working-memory/master
rm ./styleguide/a-z-word-list-term-collections/w/media/workstation/master
rm ./styleguide/a-z-word-list-term-collections/w/media/worldwide-vs-international/master
rm ./styleguide/a-z-word-list-term-collections/w/media/write-only/master
rm ./styleguide/a-z-word-list-term-collections/w/media/write-protect-write-protected/master
rm ./styleguide/a-z-word-list-term-collections/x/media/x-axis/master
rm ./styleguide/a-z-word-list-term-collections/x/media/x-coordinate/master
rm ./styleguide/a-z-word-list-term-collections/x/media/xon-xoff/master
rm ./styleguide/a-z-word-list-term-collections/x/media/x/master
rm ./styleguide/a-z-word-list-term-collections/y/media/y-axis/master
rm ./styleguide/a-z-word-list-term-collections/y/media/y-coordinate/master
rm ./styleguide/a-z-word-list-term-collections/z/media/z-axis/master
rm ./styleguide/a-z-word-list-term-collections/z/media/zero-zeros/master
rm ./styleguide/a-z-word-list-term-collections/z/media/zip-code/master
rm ./styleguide/a-z-word-list-term-collections/z/media/zoom-in-zoom-out/master
rm ./styleguide/a-z-word-list-term-collections/z/media/z/master
rm ./styleguide/accessibility/media/accessibility-guidelines-requirements/master
rm ./styleguide/accessibility/media/colors-patterns-text-graphics-design/master
rm ./styleguide/accessibility/media/graphics-design-media/master
rm ./styleguide/accessibility/media/writing-all-abilities/master
rm ./styleguide/media/acronyms/master
rm ./styleguide/media/bias-free-communication/master
rm ./styleguide/media/brand-voice-above-all-simple-human/master
rm ./styleguide/media/capitalization/master
rm ./styleguide/checklists/media/accessibility-checklist/master
rm ./styleguide/checklists/media/bias-free-communication-checklist/master
rm ./styleguide/checklists/media/blogs-communities-checklist/master
rm ./styleguide/checklists/media/capitalization-checklist/master
rm ./styleguide/checklists/media/checklists/master
rm ./styleguide/checklists/media/content-planning-checklist/master
rm ./styleguide/checklists/media/design-planning-checklist/master
rm ./styleguide/checklists/media/developer-content-checklist/master
rm ./styleguide/checklists/media/final-publishing-checklist/master
rm ./styleguide/checklists/media/global-communications-checklist/master
rm ./styleguide/checklists/media/grammar-parts-of-speech-checklist/master
rm ./styleguide/checklists/media/images-video-checklist/master
rm ./styleguide/checklists/media/legal-content-checklist/master
rm ./styleguide/checklists/media/new-products-checklist/master
rm ./styleguide/checklists/media/numbers-checklist/master
rm ./styleguide/checklists/media/procedures-instructions-checklist/master
rm ./styleguide/checklists/media/punctuation-checklist/master
rm ./styleguide/checklists/media/responsive-content-checklist/master
rm ./styleguide/checklists/media/scannable-content-checklist/master
rm ./styleguide/checklists/media/search-writing-checklist/master
rm ./styleguide/checklists/media/security-safety-privacy-content-checklist/master
rm ./styleguide/checklists/media/text-formatting-checklist/master
rm ./styleguide/checklists/media/ui-text-design-checklist/master
rm ./styleguide/checklists/media/urls-web-addresses-checklist/master
rm ./styleguide/checklists/media/word-choice-checklist/master
rm ./styleguide/media/content-planning/master
rm ./styleguide/media/design-planning/master
rm ./styleguide/developer-content/media/code-examples/master
rm ./styleguide/developer-content/media/formatting-developer-text-elements/master
rm ./styleguide/developer-content/media/index/master
rm ./styleguide/developer-content/media/reference-documentation/master
rm ./styleguide/media/final-publishing-check/master
rm ./styleguide/global-communications/media/art/master
rm ./styleguide/global-communications/media/currency/master
rm ./styleguide/global-communications/media/examples-scenarios/master
rm ./styleguide/global-communications/media/index/master
rm ./styleguide/global-communications/media/legal-considerations/master
rm ./styleguide/global-communications/media/names-contact-information/master
rm ./styleguide/global-communications/media/time-place/master
rm ./styleguide/global-communications/media/web-software-html-considerations/master
rm ./styleguide/global-communications/media/writing-tips/master
rm ./styleguide/grammar/media/dangling-misplaced-modifiers/master
rm ./styleguide/grammar/media/grammar-and-parts-of-speech/master
rm ./styleguide/grammar/media/ing-words/master
rm ./styleguide/grammar/media/nouns-pronouns/master
rm ./styleguide/grammar/media/person/master
rm ./styleguide/grammar/media/prepositions/master
rm ./styleguide/grammar/media/verbs/master
rm ./styleguide/images-video/media/illustrations/master
rm ./styleguide/images-video/media/index/master
rm ./styleguide/images-video/media/network-traffic-flows/master
rm ./styleguide/images-video/media/photos/master
rm ./styleguide/images-video/media/screenshots/master
rm ./styleguide/images-video/media/video/master
rm ./styleguide/legal-content/media/copyrights-trademarks/master
rm ./styleguide/legal-content/media/downloadable-software/master
rm ./styleguide/legal-content/media/fictitious-names-domains-addresses/master
rm ./styleguide/legal-content/media/index/master
rm ./styleguide/legal-content/media/legal-issues-types-of-content/master
rm ./styleguide/legal-content/media/red-flag-terms/master
rm ./styleguide/new-products/media/code-names/master
rm ./styleguide/new-products/media/name-development/master
rm ./styleguide/new-products/media/new-products/master
rm ./styleguide/new-products/media/product-previews/master
rm ./styleguide/new-products/media/system-requirements/master
rm ./styleguide/media/numbers/master
rm ./styleguide/procedures-instructions/media/describing-alternative-input-methods/master
rm ./styleguide/procedures-instructions/media/describing-interactions-with-ui/master
rm ./styleguide/procedures-instructions/media/formatting-text-in-instructions/master
rm ./styleguide/procedures-instructions/media/index/master
rm ./styleguide/procedures-instructions/media/writing-step-by-step-instructions/master
rm ./styleguide/punctuation/media/apostrophes/master
rm ./styleguide/punctuation/media/colons/master
rm ./styleguide/punctuation/media/commas/master
rm ./styleguide/punctuation/dashes-hyphens/media/ellipses/master
rm ./styleguide/punctuation/dashes-hyphens/media/emes/master
rm ./styleguide/punctuation/dashes-hyphens/media/enes/master
rm ./styleguide/punctuation/dashes-hyphens/media/exclamation-points/master
rm ./styleguide/punctuation/dashes-hyphens/media/hyphens/master
rm ./styleguide/punctuation/dashes-hyphens/media/index/master
rm ./styleguide/punctuation/dashes-hyphens/media/slashes/master
rm ./styleguide/punctuation/media/formatting-punctuation/master
rm ./styleguide/punctuation/media/index/master
rm ./styleguide/punctuation/media/periods/master
rm ./styleguide/punctuation/media/question-marks/master
rm ./styleguide/punctuation/media/quotation-marks/master
rm ./styleguide/punctuation/media/semicolons/master
rm ./styleguide/media/responsive-content/master
rm ./styleguide/scannable-content/media/headings/master
rm ./styleguide/scannable-content/media/index/master
rm ./styleguide/scannable-content/media/lists/master
rm ./styleguide/scannable-content/media/pull-quotes/master
rm ./styleguide/scannable-content/media/sidebars/master
rm ./styleguide/scannable-content/media/tables/master
rm ./styleguide/media/search-writing/master
rm ./styleguide/media/security-safety-privacy-content/master
rm ./styleguide/media/social-mediablogs-social-media/master
rm ./styleguide/media/social-mediablogs/master
rm ./styleguide/media/social-mediacommunities/master
rm ./styleguide/media/social-mediahashtags/master
rm ./styleguide/text-formatting/media/formatting-common-text-elements/master
rm ./styleguide/text-formatting/media/formatting-titles/master
rm ./styleguide/text-formatting/media/index/master
rm ./styleguide/text-formatting/using-type/media/dont-compress-line-spacing/master
rm ./styleguide/text-formatting/using-type/media/index/master
rm ./styleguide/text-formatting/using-type/media/use-left-alignment/master
rm ./styleguide/text-formatting/using-type/media/use-segoe-font-family/master
rm ./styleguide/text-formatting/using-type/media/use-sentence-style-capitalization/master
rm ./styleguide/media/top-10-tips-style-voice/master
rm ./styleguide/media/ui-text-content-design/master
rm ./styleguide/media/urls-web-addresses/master
rm ./styleguide/welcome/media/editorial-board/master
rm ./styleguide/welcome/media/guide-how-to/master
rm ./styleguide/welcome/media/index/master
rm ./styleguide/welcome/media/stay-connected/master
rm ./styleguide/welcome/media/style-references/master
rm ./styleguide/welcome/media/whats-new/master
rm ./styleguide/word-choice/media/avoid-jargon/master
rm ./styleguide/word-choice/media/dont-use-common-words-in-new-ways/master
rm ./styleguide/word-choice/media/index/master
rm ./styleguide/word-choice/media/use-contractions/master
rm ./styleguide/word-choice/media/use-simple-words-concise-sentences/master
rm ./styleguide/word-choice/media/use-technical-terms-carefully/master
rm ./styleguide/word-choice/media/use-us-spelling-avoid-non-english-words/master
